# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.2
language: objective-c
xcode_workspace: DDMockiOS.xcworkspace
xcode_scheme: DDMockiOSTests
xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone X
